//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printing_Photo_Online
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Digital_Photo_PrintEntities : DbContext
    {
        public Digital_Photo_PrintEntities()
            : base("name=Digital_Photo_PrintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<Photograph> Photographs { get; set; }
        public DbSet<Price_Info> Price_Info { get; set; }
        public DbSet<user> users { get; set; }
    }
}
